// api/_lib/supabase.js
//
// Thin data-access layer (roadmap D7 — "keep Supabase access code isolated
// behind a thin data-access module, not scattered raw calls throughout the
// app, so a future database migration stays cheap"). This is the ONLY file
// in the whole codebase that imports @supabase/supabase-js or talks to the
// database directly. If Alex ever migrates off Supabase, this is the only
// file that needs to change.

const { createClient } = require('@supabase/supabase-js');

let client = null;

function getClient() {
  if (!client) {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
    if (!url || !key) {
      throw new Error('SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are not set');
    }
    client = createClient(url, key, {
      auth: { persistSession: false },
    });
  }
  return client;
}

/**
 * Create a new split row. Caller supplies the short id (already generated by
 * api/_lib/validate.js's generateSplitId()).
 *
 * @param {object} params
 * @param {string} params.id
 * @param {Array<object>} params.items
 * @param {Object<string,string[]>} params.assignments
 * @param {object} params.totals
 * @param {string} params.ownerPaymentHandle
 * @param {string} params.expiresAt - ISO timestamp
 * @returns {Promise<object>} the inserted row
 */
async function createSplit({ id, items, assignments, totals, ownerPaymentHandle, expiresAt }) {
  const supabase = getClient();
  const { data, error } = await supabase
    .from('splits')
    .insert({
      id,
      items,
      assignments,
      totals,
      owner_payment_handle: ownerPaymentHandle,
      expires_at: expiresAt,
    })
    .select()
    .single();
  if (error) throw error;
  return data;
}

/**
 * Read a split by id. Returns null if not found, or if it has passed its
 * `expires_at` (treated as "not found" from the caller's perspective —
 * MVP-1 doesn't implement the actual purge job yet, see supabase/schema.sql).
 *
 * @param {string} id
 * @returns {Promise<object|null>}
 */
async function getSplit(id) {
  const supabase = getClient();
  const { data, error } = await supabase
    .from('splits')
    .select('id, items, assignments, totals, owner_payment_handle, created_at, expires_at')
    .eq('id', id)
    .maybeSingle();
  if (error) throw error;
  if (!data) return null;
  if (data.expires_at && new Date(data.expires_at) < new Date()) return null;
  return data;
}

/**
 * Fire-and-forget insert into the anonymised analytics dataset (roadmap F7a).
 * Rows here MUST NOT carry a name, payment handle, or any reversible link
 * back to the `splits` row that produced them.
 *
 * @param {Array<{item_category: string, amount: number}>} rows
 */
async function insertAnalyticsRows(rows) {
  if (!rows || rows.length === 0) return;
  const supabase = getClient();
  const { error } = await supabase.from('bill_analytics').insert(rows);
  if (error) {
    // Analytics is best-effort and must never block or fail the operational
    // split creation — log and swallow rather than throw.
    console.error('bill_analytics insert failed (non-fatal):', error.message);
  }
}

module.exports = { createSplit, getSplit, insertAnalyticsRows };
