// api/_lib/supabase.js
//
// Thin data-access layer (roadmap D7 — "keep Supabase access code isolated
// behind a thin data-access module, not scattered raw calls throughout the
// app, so a future database migration stays cheap"). This is the ONLY file
// in the whole codebase that imports @supabase/supabase-js or talks to the
// database directly. If Alex ever migrates off Supabase, this is the only
// file that needs to change.

const { createClient } = require('@supabase/supabase-js');
const { computeClaimTotals } = require('./recompute');

let client = null;

function getClient() {
  if (!client) {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
    if (!url || !key) {
      throw new Error('SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are not set');
    }
    client = createClient(url, key, {
      auth: { persistSession: false },
      // Bilang's tables live under the dedicated `bilang` Postgres schema,
      // not `public` (Open Item 21, decided 2026-09-29 — see
      // supabase/schema.sql). This tells PostgREST which schema to query;
      // the corresponding "Exposed schemas" dashboard setting (Settings ->
      // API) must also list `bilang` in each Supabase project, or this
      // client will get errors reaching it even though this option is set.
      db: { schema: 'bilang' },
    });
  }
  return client;
}

const SPLIT_COLUMNS = 'id, items, assignments, totals, owner_payment_handle, created_at, expires_at';
const SPLIT_COLUMNS_WITH_ROSTER = `${SPLIT_COLUMNS}, payers, version`;

// True when the database rejected a statement because a column does not exist
// (Postgres 42703, or PostgREST's schema-cache miss PGRST204).
function isMissingColumnError(error) {
  if (!error) return false;
  if (error.code === '42703' || error.code === 'PGRST204') return true;
  return /column .*(payers|version)|(payers|version).* column/i.test(String(error.message || ''));
}

const warned = new Set();
function warnOnce(key, message) {
  if (warned.has(key)) return;
  warned.add(key);
  console.warn(message);
}

/**
 * Create a new split row. Caller supplies the short id (already generated by
 * api/_lib/validate.js's generateSplitId()).
 *
 * @param {object} params
 * @param {string} params.id
 * @param {Array<object>} params.items
 * @param {Object<string,string[]>} params.assignments
 * @param {object} params.totals
 * @param {string} params.ownerPaymentHandle
 * @param {string} params.expiresAt - ISO timestamp
 * @returns {Promise<object>} the inserted row
 */
async function createSplit({ id, items, assignments, totals, payers, ownerPaymentHandle, expiresAt }) {
  const supabase = getClient();
  const row = {
    id,
    items,
    assignments,
    totals,
    owner_payment_handle: ownerPaymentHandle,
    expires_at: expiresAt,
  };
  const insert = (r) => supabase.from('splits').insert(r).select().single();

  if (payers === undefined) {
    const { data, error } = await insert(row);
    if (error) throw error;
    return data;
  }

  const { data, error } = await insert({ ...row, payers });
  if (error && isMissingColumnError(error)) {
    // The payers column has not been added to this database yet: store the
    // split without it so creation keeps working until the migration is applied.
    warnOnce('write', 'splits.payers column is missing; storing splits without a roster until the migration is applied');
    const retry = await insert(row);
    if (retry.error) throw retry.error;
    return retry.data;
  }
  if (error) throw error;
  return data;
}

/**
 * Read a split by id. Returns null if not found, or if it has passed its
 * `expires_at` (treated as "not found" from the caller's perspective —
 * MVP-1 doesn't implement the actual purge job yet, see supabase/schema.sql).
 *
 * @param {string} id
 * @returns {Promise<object|null>}
 */
async function getSplit(id) {
  const supabase = getClient();
  const read = (columns) => supabase.from('splits').select(columns).eq('id', id).maybeSingle();

  let { data, error } = await read(SPLIT_COLUMNS_WITH_ROSTER);
  if (error && isMissingColumnError(error)) {
    // payers / version are not in this database yet: read the original columns.
    warnOnce('read', 'splits.payers / splits.version columns are missing; reading splits without them until the migration is applied');
    ({ data, error } = await read(SPLIT_COLUMNS));
  }
  if (error) throw error;
  if (!data) return null;
  if (data.expires_at && new Date(data.expires_at) < new Date()) return null;
  return data;
}

/**
 * Version-guarded write of a split's assignments AND its recomputed totals
 * (compare-and-swap; Item 21 Step 4 / R6). Applies only if the row is still
 * at `expectedVersion`, and bumps the version by one in the same statement,
 * so a caller that read a stale row changes nothing.
 *
 * The recompute (api/_lib/recompute.js's computeClaimTotals, itself a thin
 * wrapper over the shared api/_lib/totals.js arithmetic) runs just before
 * the write and its result is written in the SAME `update()` call as
 * `assignments` — one statement, guarded by the same `WHERE version =
 * expectedVersion`. If the compare-and-swap does not apply (the version
 * moved), this statement matches zero rows and NEITHER the claim NOR the
 * totals are written — there is no window in which one lands without the
 * other. Never writes `items`, the roster, or the receipt-level totals
 * fields (subtotal/service_charge/tax/grand_total): those are immutable
 * after creation and are carried through unchanged by computeClaimTotals.
 *
 * @param {string} id
 * @param {number} expectedVersion - the version the caller read
 * @param {object} assignments - the complete new assignments object
 * @param {Array<object>} items - the split's items, as read alongside `assignments`
 * @param {string[]} payers - the split's roster, as read alongside `assignments`
 * @param {object} billTotals - the split's current `totals`, as read alongside `assignments`
 * @returns {Promise<{assignments: object, totals: object, version: number}|null>}
 *   the updated row (with its freshly recomputed `totals`), or null if
 *   nobody matched (the version moved, or the row is gone)
 */
async function claimSplitItem(id, expectedVersion, assignments, items = [], payers = [], billTotals = {}) {
  const totals = computeClaimTotals(items, assignments, billTotals, payers);
  const supabase = getClient();
  const { data, error } = await supabase
    .from('splits')
    .update({ assignments, totals, version: expectedVersion + 1 })
    .eq('id', id)
    .eq('version', expectedVersion)
    .select('assignments, totals, version');
  if (error) throw error;
  return data && data.length > 0 ? data[0] : null;
}

/**
 * Fire-and-forget insert into the anonymised analytics dataset (roadmap F7a).
 * Rows here MUST NOT carry a name, payment handle, or any reversible link
 * back to the `splits` row that produced them.
 *
 * @param {Array<{item_category: string, amount: number}>} rows
 */
async function insertAnalyticsRows(rows) {
  if (!rows || rows.length === 0) return;
  const supabase = getClient();
  const { error } = await supabase.from('bill_analytics').insert(rows);
  if (error) {
    // Analytics is best-effort and must never block or fail the operational
    // split creation — log and swallow rather than throw.
    console.error('bill_analytics insert failed (non-fatal):', error.message);
  }
}

module.exports = { createSplit, getSplit, claimSplitItem, insertAnalyticsRows };
