// api/_lib/supabase.js
//
// Thin data-access layer (roadmap D7 — "keep Supabase access code isolated
// behind a thin data-access module, not scattered raw calls throughout the
// app, so a future database migration stays cheap"). This is the ONLY file
// in the whole codebase that imports @supabase/supabase-js or talks to the
// database directly. If Alex ever migrates off Supabase, this is the only
// file that needs to change.

const { createClient } = require('@supabase/supabase-js');
const { computeClaimTotals } = require('./recompute');

let client = null;

function getClient() {
  if (!client) {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
    if (!url || !key) {
      throw new Error('SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are not set');
    }
    client = createClient(url, key, {
      auth: { persistSession: false },
      // Bilang's tables live under the dedicated `bilang` Postgres schema,
      // not `public` (Open Item 21, decided 2026-09-29 — see
      // supabase/schema.sql). This tells PostgREST which schema to query;
      // the corresponding "Exposed schemas" dashboard setting (Settings ->
      // API) must also list `bilang` in each Supabase project, or this
      // client will get errors reaching it even though this option is set.
      db: { schema: 'bilang' },
    });
  }
  return client;
}

const SPLIT_COLUMNS = 'id, items, assignments, totals, owner_payment_handle, created_at, expires_at';
const SPLIT_COLUMNS_WITH_ROSTER = `${SPLIT_COLUMNS}, payers, version`;
// Item 23 (merchant name + receipt date) — a third, further-additive column
// set, same layering the payers/version columns already established: try
// the widest select first, fall back a step at a time if a migration hasn't
// landed on this database yet. See getSplit()'s fallback chain below.
const SPLIT_COLUMNS_WITH_ROSTER_AND_RECEIPT = `${SPLIT_COLUMNS_WITH_ROSTER}, merchant_name, receipt_date`;

// True when the database rejected a statement because a column does not exist
// (Postgres 42703, or PostgREST's schema-cache miss PGRST204).
function isMissingColumnError(error) {
  if (!error) return false;
  if (error.code === '42703' || error.code === 'PGRST204') return true;
  return /column .*(payers|version|merchant_name|receipt_date)|(payers|version|merchant_name|receipt_date).* column/i.test(
    String(error.message || '')
  );
}

const warned = new Set();
function warnOnce(key, message) {
  if (warned.has(key)) return;
  warned.add(key);
  console.warn(message);
}

/**
 * Create a new split row. Caller supplies the short id (already generated by
 * api/_lib/validate.js's generateSplitId()).
 *
 * @param {object} params
 * @param {string} params.id
 * @param {Array<object>} params.items
 * @param {Object<string,string[]>} params.assignments
 * @param {object} params.totals
 * @param {string} params.ownerPaymentHandle
 * @param {string} params.expiresAt - ISO timestamp
 * @param {string} [params.merchantName] - Item 23, D4. Omit (undefined) to
 *   skip the column entirely; pass null explicitly for "read but illegible".
 * @param {string} [params.receiptDate] - Item 23, D4. Same undefined/null rule.
 * @param {string} [params.accountId] - Item 10 Step 8. The signed-in creator's
 *   account id (from requireAccount), persisted to splits.account_id. Omit
 *   (undefined) to leave the column unset; never returned by GET /api/split.
 * @returns {Promise<object>} the inserted row
 */
async function createSplit({
  id,
  items,
  assignments,
  totals,
  payers,
  ownerPaymentHandle,
  expiresAt,
  merchantName,
  receiptDate,
  accountId,
}) {
  const supabase = getClient();
  const row = {
    id,
    items,
    assignments,
    totals,
    owner_payment_handle: ownerPaymentHandle,
    expires_at: expiresAt,
    ...(accountId === undefined ? {} : { account_id: accountId }),
  };
  const insert = (r) => supabase.from('splits').insert(r).select().single();

  const withPayers = payers === undefined ? row : { ...row, payers };
  // Item 23, D4: same undefined-means-"don't send the column" convention as
  // payers above. A caller that DID get a value from parse (even a null —
  // "read but illegible") passes it through; a caller with no opinion on
  // these two fields at all (legacy call shape) omits them.
  const withReceipt =
    merchantName === undefined && receiptDate === undefined
      ? withPayers
      : { ...withPayers, merchant_name: merchantName ?? null, receipt_date: receiptDate ?? null };

  const { data, error } = await insert(withReceipt);
  if (!error) return data;
  if (!isMissingColumnError(error)) throw error;

  // Progressively narrower column sets, in case only some of Item 23's /
  // Item 24's additive migrations have landed on this database yet — same
  // graceful-fallback discipline the payers/version columns established
  // (real split rows exist post-Item-24, so a hard migration-order
  // dependency here would break existing writes).
  if (withReceipt !== withPayers) {
    warnOnce(
      'write-receipt',
      'splits.merchant_name / splits.receipt_date columns are missing; storing splits without them until the migration is applied'
    );
    const retry = await insert(withPayers);
    if (!retry.error) return retry.data;
    if (!isMissingColumnError(retry.error)) throw retry.error;
  }

  if (withPayers !== row) {
    // The payers column has not been added to this database yet: store the
    // split without it so creation keeps working until the migration is applied.
    warnOnce('write', 'splits.payers column is missing; storing splits without a roster until the migration is applied');
    const retry2 = await insert(row);
    if (retry2.error) throw retry2.error;
    return retry2.data;
  }

  throw error;
}

/**
 * Read a split by id. Returns null if not found, or if it has passed its
 * `expires_at` (treated as "not found" from the caller's perspective —
 * MVP-1 doesn't implement the actual purge job yet, see supabase/schema.sql).
 *
 * @param {string} id
 * @returns {Promise<object|null>}
 */
async function getSplit(id) {
  const supabase = getClient();
  const read = (columns) => supabase.from('splits').select(columns).eq('id', id).maybeSingle();

  let { data, error } = await read(SPLIT_COLUMNS_WITH_ROSTER_AND_RECEIPT);
  if (error && isMissingColumnError(error)) {
    // Item 23's merchant_name / receipt_date are not in this database yet:
    // step down to the roster columns only.
    warnOnce(
      'read-receipt',
      'splits.merchant_name / splits.receipt_date columns are missing; reading splits without them until the migration is applied'
    );
    ({ data, error } = await read(SPLIT_COLUMNS_WITH_ROSTER));
  }
  if (error && isMissingColumnError(error)) {
    // payers / version are not in this database yet either: read the original columns.
    warnOnce('read', 'splits.payers / splits.version columns are missing; reading splits without them until the migration is applied');
    ({ data, error } = await read(SPLIT_COLUMNS));
  }
  if (error) throw error;
  if (!data) return null;
  if (data.expires_at && new Date(data.expires_at) < new Date()) return null;
  return data;
}

/**
 * Version-guarded write of a split's assignments AND its recomputed totals
 * (compare-and-swap; Item 21 Step 4 / R6). Applies only if the row is still
 * at `expectedVersion`, and bumps the version by one in the same statement,
 * so a caller that read a stale row changes nothing.
 *
 * The recompute (api/_lib/recompute.js's computeClaimTotals, itself a thin
 * wrapper over the shared api/_lib/totals.js arithmetic) runs just before
 * the write and its result is written in the SAME `update()` call as
 * `assignments` — one statement, guarded by the same `WHERE version =
 * expectedVersion`. If the compare-and-swap does not apply (the version
 * moved), this statement matches zero rows and NEITHER the claim NOR the
 * totals are written — there is no window in which one lands without the
 * other. Never writes `items`, the roster, or the receipt-level totals
 * fields (subtotal/service_charge/tax/grand_total): those are immutable
 * after creation and are carried through unchanged by computeClaimTotals.
 *
 * @param {string} id
 * @param {number} expectedVersion - the version the caller read
 * @param {object} assignments - the complete new assignments object
 * @param {Array<object>} items - the split's items, as read alongside `assignments`
 * @param {string[]} payers - the split's roster, as read alongside `assignments`
 * @param {object} billTotals - the split's current `totals`, as read alongside `assignments`
 * @returns {Promise<{assignments: object, totals: object, version: number}|null>}
 *   the updated row (with its freshly recomputed `totals`), or null if
 *   nobody matched (the version moved, or the row is gone)
 */
async function claimSplitItem(id, expectedVersion, assignments, items = [], payers = [], billTotals = {}) {
  const totals = computeClaimTotals(items, assignments, billTotals, payers);
  const supabase = getClient();
  const { data, error } = await supabase
    .from('splits')
    .update({ assignments, totals, version: expectedVersion + 1 })
    .eq('id', id)
    .eq('version', expectedVersion)
    .select('assignments, totals, version');
  if (error) throw error;
  return data && data.length > 0 ? data[0] : null;
}

/**
 * Fire-and-forget insert into the anonymised analytics dataset (roadmap F7a).
 * Rows here MUST NOT carry a name, payment handle, or any reversible link
 * back to the `splits` row that produced them.
 *
 * @param {Array<{item_category: string, amount: number}>} rows
 */
async function insertAnalyticsRows(rows) {
  if (!rows || rows.length === 0) return;
  const supabase = getClient();
  const { error } = await supabase.from('bill_analytics').insert(rows);
  if (error) {
    // Analytics is best-effort and must never block or fail the operational
    // split creation — log and swallow rather than throw.
    console.error('bill_analytics insert failed (non-fatal):', error.message);
  }
}

// ---- Item 10 Checkpoint 2, Step 7 --------------------------------------

/**
 * Insert-or-detect-existing for the `accounts` table, keyed by the Supabase
 * auth user id (D11). Reports whether this call INSERTED a new row or
 * matched an existing one — POST /api/auth/verify-code needs that
 * distinction to decide whether the D15 terms-acceptance requirement
 * applies (first-time sign-in only; a returning user is never re-asked).
 *
 * Implementation note on atomicity (read before changing this): plans
 * §10.3 describes the accounts insert and the (first-time-only)
 * terms_acceptances insert as happening "in the same transaction." A real
 * Postgres transaction spanning two separate table writes would need a
 * database function (an RPC) — that is a schema change, and Checkpoint 2's
 * brief is explicit that no schema SQL is to be written or run beyond what
 * was already needed. This function is deliberately just "insert, and
 * report which case it was" — api/auth/verify-code.js achieves the same
 * *observable* guarantee (no accounts row can be left behind with no
 * matching terms_acceptances row) with an explicit compensating rollback
 * (deleteOrphanedAccount, below) if the terms-acceptance insert fails.
 * Flagged for Alex: if true DB-level atomicity via an RPC is wanted later,
 * that is a schema addition and should be requested explicitly.
 *
 * @param {string} id - the Supabase auth user id (session.user.id)
 * @returns {Promise<{account: {id: string, created_at: string}, inserted: boolean}>}
 */
async function upsertAccount(id) {
  const supabase = getClient();
  const { data, error } = await supabase.from('accounts').insert({ id }).select().single();
  if (!error) {
    return { account: data, inserted: true };
  }
  // 23505 = unique_violation (Postgres) — the row already exists, i.e. this
  // is a returning user, not a failure.
  if (error.code === '23505') {
    const { data: existing, error: selectError } = await supabase
      .from('accounts')
      .select('id, created_at')
      .eq('id', id)
      .single();
    if (selectError) throw selectError;
    return { account: existing, inserted: false };
  }
  throw error;
}

/**
 * D15: write the timestamped, versioned terms-acceptance record. Called
 * ONLY when upsertAccount() reported `inserted: true` — a returning user is
 * never asked to re-accept, and this function does not itself check that;
 * the caller (api/auth/verify-code.js) enforces the "only on insert" rule.
 *
 * @param {string} accountId
 * @param {string} termsVersion
 */
async function recordTermsAcceptance(accountId, termsVersion) {
  const supabase = getClient();
  const { error } = await supabase.from('terms_acceptances').insert({
    account_id: accountId,
    terms_kind: 'signup',
    terms_version: termsVersion,
  });
  if (error) throw error;
}

/**
 * Compensating rollback for D15's "an account must never exist with no
 * corresponding acceptance record" invariant — used only when
 * upsertAccount() just inserted a brand-new row and either the caller
 * declines/omits terms acceptance, or the subsequent recordTermsAcceptance
 * insert itself fails. NOT a general-purpose account-deletion feature —
 * Item 18 owns actual user-requested account deletion, separately and
 * later. This exists solely to undo THIS function's own just-made insert,
 * within the same request, before any cookie is ever set.
 *
 * Deliberately named distinctly from anything Item 18 will build, so a
 * future reader searching for "account deletion" does not find this and
 * mistake it for that feature.
 *
 * @param {string} id
 */
async function deleteOrphanedAccount(id) {
  const supabase = getClient();
  const { error } = await supabase.from('accounts').delete().eq('id', id);
  if (error) throw error;
}

/**
 * Tony's approved MVP1 "cheap half" (2026-10-10, relayed via coordinator,
 * bilang-pm-tracker.md v2.80 change-log): read back just the one column
 * GET /api/auth/session needs to decide whether a silent sync is due. No
 * banner, no email, no copy — the visible notification stays on backlog.
 *
 * @param {string} id
 * @returns {Promise<string|null>}
 */
async function getTermsVersionSeen(id) {
  const supabase = getClient();
  const { data, error } = await supabase.from('accounts').select('terms_version_seen').eq('id', id).single();
  if (error) throw error;
  return data.terms_version_seen;
}

/**
 * Silently records that this account has now seen `version`. Called only
 * when GET /api/auth/session has already determined the stored value
 * differs from the currently published version — this function itself does
 * not compare, it just writes.
 *
 * @param {string} id
 * @param {string} version
 */
async function updateTermsVersionSeen(id, version) {
  const supabase = getClient();
  const { error } = await supabase.from('accounts').update({ terms_version_seen: version }).eq('id', id);
  if (error) throw error;
}

module.exports = {
  createSplit,
  getSplit,
  claimSplitItem,
  insertAnalyticsRows,
  upsertAccount,
  recordTermsAcceptance,
  deleteOrphanedAccount,
  getTermsVersionSeen,
  updateTermsVersionSeen,
};
